version: '3.8'

services:
  database:
    image: postgres:16 
    container_name: bank_db_container
    environment:
      POSTGRES_USER: admin       
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: bankowosc_db      # Nazwa bazy danych, która powstanie na starcie
    ports:
      - "5432:5432"  # Przekierowanie portu:  5432 -> Kontener (5432)
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Tu będą zapisywane fizyczne dane (trwałość)
    restart: always
